//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ornament.Identity {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ornament.Identity.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password must be at Least one letter, number or symbol, and within 8 to 30 characters..
        /// </summary>
        public static string alertPassword_CharError {
            get {
                return ResourceManager.GetString("alertPassword_CharError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Create time.
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Deny Access.
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Confirm Email Address.
        /// </summary>
        public static string EmailConfirm {
            get {
                return ResourceManager.GetString("EmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please input right format email address.
        /// </summary>
        public static string EmailNotRightFormat {
            get {
                return ResourceManager.GetString("EmailNotRightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to , {0} attempts remain before account is locked.
        /// </summary>
        public static string error_login_remind_attempts {
            get {
                return ResourceManager.GetString("error_login_remind_attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Login ID or Password is not match..
        /// </summary>
        public static string error_LoginError {
            get {
                return ResourceManager.GetString("error_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Deny.
        /// </summary>
        public static string error_UserIsDeny {
            get {
                return ResourceManager.GetString("error_UserIsDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User is lockout, .
        /// </summary>
        public static string error_UserIsLockout {
            get {
                return ResourceManager.GetString("error_UserIsLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please contact your administrator..
        /// </summary>
        public static string error_UserIsLockout_contact_administrator {
            get {
                return ResourceManager.GetString("error_UserIsLockout_contact_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please try again after {0} miniutes..
        /// </summary>
        public static string error_UserIsLockout_retry_after_mins {
            get {
                return ResourceManager.GetString("error_UserIsLockout_retry_after_mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email Approved.
        /// </summary>
        public static string IsEmailApproved {
            get {
                return ResourceManager.GetString("IsEmailApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Lockout.
        /// </summary>
        public static string IsLockout {
            get {
                return ResourceManager.GetString("IsLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Last activity time.
        /// </summary>
        public static string LastActivityTime {
            get {
                return ResourceManager.GetString("LastActivityTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to LastUserLockedTime.
        /// </summary>
        public static string LastLockTime {
            get {
                return ResourceManager.GetString("LastLockTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Last login time.
        /// </summary>
        public static string LastLoginTime {
            get {
                return ResourceManager.GetString("LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Last password changed time.
        /// </summary>
        public static string LastPasswordChangedTime {
            get {
                return ResourceManager.GetString("LastPasswordChangedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Last update time.
        /// </summary>
        public static string LastUpdateTime {
            get {
                return ResourceManager.GetString("LastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Login ID.
        /// </summary>
        public static string LoginId {
            get {
                return ResourceManager.GetString("LoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to LoginID should be between 6 and 20, It should be number underscrope and letter and case sense..
        /// </summary>
        public static string LoginNotCorrectFormat {
            get {
                return ResourceManager.GetString("LoginNotCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name&apos;s length should be 1~30.
        /// </summary>
        public static string NameOverMaxLength {
            get {
                return ResourceManager.GetString("NameOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Operators.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Organization.
        /// </summary>
        public static string Org {
            get {
                return ResourceManager.GetString("Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Child Org&apos;s Count.
        /// </summary>
        public static string Org_OrgCount_Child_Org_s_Count {
            get {
                return ResourceManager.GetString("Org_OrgCount_Child_Org_s_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to PageIndex should greater than zero or equal zero..
        /// </summary>
        public static string PageIndex_should_greater_than_zero_ {
            get {
                return ResourceManager.GetString("PageIndex_should_greater_than_zero_", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to pageSize should greater than zero..
        /// </summary>
        public static string PageSize_should_greater_than_zero {
            get {
                return ResourceManager.GetString("PageSize_should_greater_than_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password answer.
        /// </summary>
        public static string PasswordAnswer {
            get {
                return ResourceManager.GetString("PasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Re-enter Password.
        /// </summary>
        public static string PasswordConfirm {
            get {
                return ResourceManager.GetString("PasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password question .
        /// </summary>
        public static string PasswordQuestion {
            get {
                return ResourceManager.GetString("PasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Length should be unbder 30 .
        /// </summary>
        public static string PasswordQuestionAnswerOverMaxLength {
            get {
                return ResourceManager.GetString("PasswordQuestionAnswerOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Permission Name.
        /// </summary>
        public static string PermissionName {
            get {
                return ResourceManager.GetString("PermissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Registry time.
        /// </summary>
        public static string RegistryTime {
            get {
                return ResourceManager.GetString("RegistryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Remark.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Remark&apos;s length should be less than 200.
        /// </summary>
        public static string RemarkOverMaxLength {
            get {
                return ResourceManager.GetString("RemarkOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please input loginId..
        /// </summary>
        public static string RequireLoginId {
            get {
                return ResourceManager.GetString("RequireLoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please input name..
        /// </summary>
        public static string RequireName {
            get {
                return ResourceManager.GetString("RequireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please input password..
        /// </summary>
        public static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please input question&apos;s answer.
        /// </summary>
        public static string RequirePasswordAnswer {
            get {
                return ResourceManager.GetString("RequirePasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please entry question..
        /// </summary>
        public static string RequirePasswordQuestion {
            get {
                return ResourceManager.GetString("RequirePasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to please input role&apos;s name.
        /// </summary>
        public static string RequireRoleName {
            get {
                return ResourceManager.GetString("RequireRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The length of role&apos;s name should be less than 20.
        /// </summary>
        public static string RoleNameOverMaxLength {
            get {
                return ResourceManager.GetString("RoleNameOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The length of role&apos;s Remark should be less than 100.
        /// </summary>
        public static string RoleRemarkOverMaxLength {
            get {
                return ResourceManager.GetString("RoleRemarkOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Time zone.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User Group.
        /// </summary>
        public static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
    }
}
