//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.membership {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sitemap() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.membership.sitemap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Assign 的本地化字符串。
        /// </summary>
        internal static string assignTitle {
            get {
                return ResourceManager.GetString("assignTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Initialization 的本地化字符串。
        /// </summary>
        internal static string dataInitTitle {
            get {
                return ResourceManager.GetString("dataInitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Notify 的本地化字符串。
        /// </summary>
        internal static string EmailsTitle {
            get {
                return ResourceManager.GetString("EmailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Event Log 的本地化字符串。
        /// </summary>
        internal static string eventLogTitle {
            get {
                return ResourceManager.GetString("eventLogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign Roles 的本地化字符串。
        /// </summary>
        internal static string groupAssignRoleTitle {
            get {
                return ResourceManager.GetString("groupAssignRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign Users 的本地化字符串。
        /// </summary>
        internal static string groupAssignUserTitle {
            get {
                return ResourceManager.GetString("groupAssignUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Usergroup 的本地化字符串。
        /// </summary>
        internal static string groupCreateTitle {
            get {
                return ResourceManager.GetString("groupCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string groupEditTitle {
            get {
                return ResourceManager.GetString("groupEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Usergroups 的本地化字符串。
        /// </summary>
        internal static string groupListTitle {
            get {
                return ResourceManager.GetString("groupListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string homeTtitle {
            get {
                return ResourceManager.GetString("homeTtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MemberShip 的本地化字符串。
        /// </summary>
        internal static string MemberShipsTitle {
            get {
                return ResourceManager.GetString("MemberShipsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member 的本地化字符串。
        /// </summary>
        internal static string membershipTitle {
            get {
                return ResourceManager.GetString("membershipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Org 的本地化字符串。
        /// </summary>
        internal static string orgCreateTitle {
            get {
                return ResourceManager.GetString("orgCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string orgEditTitle {
            get {
                return ResourceManager.GetString("orgEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Org list 的本地化字符串。
        /// </summary>
        internal static string orgListTitle {
            get {
                return ResourceManager.GetString("orgListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create New Permission 的本地化字符串。
        /// </summary>
        internal static string permissionCreateTitle {
            get {
                return ResourceManager.GetString("permissionCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Permission 的本地化字符串。
        /// </summary>
        internal static string permissionDeleteTitle {
            get {
                return ResourceManager.GetString("permissionDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Permission 的本地化字符串。
        /// </summary>
        internal static string permissionEditTitle {
            get {
                return ResourceManager.GetString("permissionEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission list 的本地化字符串。
        /// </summary>
        internal static string permissionListTitle {
            get {
                return ResourceManager.GetString("permissionListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personal 的本地化字符串。
        /// </summary>
        internal static string personalTitle {
            get {
                return ResourceManager.GetString("personalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Role 的本地化字符串。
        /// </summary>
        internal static string roleCreateTitle {
            get {
                return ResourceManager.GetString("roleCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string roleDeleteTitle {
            get {
                return ResourceManager.GetString("roleDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string roleEditTitle {
            get {
                return ResourceManager.GetString("roleEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role list 的本地化字符串。
        /// </summary>
        internal static string roleListTitle {
            get {
                return ResourceManager.GetString("roleListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string settingsTitle {
            get {
                return ResourceManager.GetString("settingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        internal static string systemTitle {
            get {
                return ResourceManager.GetString("systemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create User  的本地化字符串。
        /// </summary>
        internal static string userCreateTitle {
            get {
                return ResourceManager.GetString("userCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit User 的本地化字符串。
        /// </summary>
        internal static string userEditTitle {
            get {
                return ResourceManager.GetString("userEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User list 的本地化字符串。
        /// </summary>
        internal static string userListTitle {
            get {
                return ResourceManager.GetString("userListTitle", resourceCulture);
            }
        }
    }
}
