//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.message {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sitemap() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.message.sitemap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string newsCreateTitle {
            get {
                return ResourceManager.GetString("newsCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string newsEditTitle {
            get {
                return ResourceManager.GetString("newsEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 News 的本地化字符串。
        /// </summary>
        internal static string newsIndexTitle {
            get {
                return ResourceManager.GetString("newsIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 News Type 的本地化字符串。
        /// </summary>
        internal static string newsTypeIndexTitle {
            get {
                return ResourceManager.GetString("newsTypeIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string notifyTypeCreateTitle {
            get {
                return ResourceManager.GetString("notifyTypeCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string notifyTypeEditTitle {
            get {
                return ResourceManager.GetString("notifyTypeEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notify Type 的本地化字符串。
        /// </summary>
        internal static string notifyTypeTitle {
            get {
                return ResourceManager.GetString("notifyTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        internal static string templateCreateTitle {
            get {
                return ResourceManager.GetString("templateCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string templateEditTitle {
            get {
                return ResourceManager.GetString("templateEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Templates 的本地化字符串。
        /// </summary>
        internal static string templateTitle {
            get {
                return ResourceManager.GetString("templateTitle", resourceCulture);
            }
        }
    }
}
