//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sitemap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Web.sitemap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Org.
        /// </summary>
        internal static string createOrg_title {
            get {
                return ResourceManager.GetString("createOrg.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role.
        /// </summary>
        internal static string createRole_title {
            get {
                return ResourceManager.GetString("createRole.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Usergroup.
        /// </summary>
        internal static string createUserGroup_title {
            get {
                return ResourceManager.GetString("createUserGroup.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        internal static string createUser_title {
            get {
                return ResourceManager.GetString("createUser.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Initialization.
        /// </summary>
        internal static string dataInit_title {
            get {
                return ResourceManager.GetString("dataInit.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log.
        /// </summary>
        internal static string eventLog_title {
            get {
                return ResourceManager.GetString("eventLog.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home_title {
            get {
                return ResourceManager.GetString("home.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string membership_title {
            get {
                return ResourceManager.GetString("membership.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org list.
        /// </summary>
        internal static string orgIndex_title {
            get {
                return ResourceManager.GetString("orgIndex.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission list.
        /// </summary>
        internal static string permissionList_title {
            get {
                return ResourceManager.GetString("permissionList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role list.
        /// </summary>
        internal static string roleList_title {
            get {
                return ResourceManager.GetString("roleList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string system_title {
            get {
                return ResourceManager.GetString("system.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usergroup list.
        /// </summary>
        internal static string userGroupList_title {
            get {
                return ResourceManager.GetString("userGroupList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        internal static string userList_title {
            get {
                return ResourceManager.GetString("userList.title", resourceCulture);
            }
        }
    }
}
