//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ornament.MemberShip.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ornament.MemberShip.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Re-enter Password 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create time 的本地化字符串。
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Password 的本地化字符串。
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deny Access 的本地化字符串。
        /// </summary>
        public static string Deny {
            get {
                return ResourceManager.GetString("Deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Address 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input right format email address 的本地化字符串。
        /// </summary>
        public static string EmailNotRightFormat {
            get {
                return ResourceManager.GetString("EmailNotRightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , {0} attempts remain before account is locked 的本地化字符串。
        /// </summary>
        public static string error_login_remind_attempts {
            get {
                return ResourceManager.GetString("error_login_remind_attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login ID or Password is not match. 的本地化字符串。
        /// </summary>
        public static string error_LoginError {
            get {
                return ResourceManager.GetString("error_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deny 的本地化字符串。
        /// </summary>
        public static string error_UserIsDeny {
            get {
                return ResourceManager.GetString("error_UserIsDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User is lockout,  的本地化字符串。
        /// </summary>
        public static string error_UserIsLockout {
            get {
                return ResourceManager.GetString("error_UserIsLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please contact your administrator. 的本地化字符串。
        /// </summary>
        public static string error_UserIsLockout_contact_administrator {
            get {
                return ResourceManager.GetString("error_UserIsLockout_contact_administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please try again after {0} miniutes. 的本地化字符串。
        /// </summary>
        public static string error_UserIsLockout_retry_after_mins {
            get {
                return ResourceManager.GetString("error_UserIsLockout_retry_after_mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Approved 的本地化字符串。
        /// </summary>
        public static string IsEmailApproved {
            get {
                return ResourceManager.GetString("IsEmailApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lockout 的本地化字符串。
        /// </summary>
        public static string IsLockout {
            get {
                return ResourceManager.GetString("IsLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last activity time 的本地化字符串。
        /// </summary>
        public static string LastActivityTime {
            get {
                return ResourceManager.GetString("LastActivityTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LastUserLockedTime 的本地化字符串。
        /// </summary>
        public static string LastLockTime {
            get {
                return ResourceManager.GetString("LastLockTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last login time 的本地化字符串。
        /// </summary>
        public static string LastLoginTime {
            get {
                return ResourceManager.GetString("LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last password changed time 的本地化字符串。
        /// </summary>
        public static string LastPasswordChangedTime {
            get {
                return ResourceManager.GetString("LastPasswordChangedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last update time 的本地化字符串。
        /// </summary>
        public static string LastUpdateTime {
            get {
                return ResourceManager.GetString("LastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login ID 的本地化字符串。
        /// </summary>
        public static string LoginId {
            get {
                return ResourceManager.GetString("LoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginID should be between 6 and 20, It should be number underscrope and letter and case sense. 的本地化字符串。
        /// </summary>
        public static string LoginNotCorrectFormat {
            get {
                return ResourceManager.GetString("LoginNotCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name&apos;s length should be 1~30 的本地化字符串。
        /// </summary>
        public static string NameOverMaxLength {
            get {
                return ResourceManager.GetString("NameOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Password 的本地化字符串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operators 的本地化字符串。
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Organization 的本地化字符串。
        /// </summary>
        public static string Org {
            get {
                return ResourceManager.GetString("Org", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Child Org&apos;s Count 的本地化字符串。
        /// </summary>
        public static string Org_OrgCount_Child_Org_s_Count {
            get {
                return ResourceManager.GetString("Org_OrgCount_Child_Org_s_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageIndex should greater than zero or equal zero. 的本地化字符串。
        /// </summary>
        public static string PageIndex_should_greater_than_zero_ {
            get {
                return ResourceManager.GetString("PageIndex_should_greater_than_zero_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pageSize should greater than zero. 的本地化字符串。
        /// </summary>
        public static string PageSize_should_greater_than_zero {
            get {
                return ResourceManager.GetString("PageSize_should_greater_than_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password answer 的本地化字符串。
        /// </summary>
        public static string PasswordAnswer {
            get {
                return ResourceManager.GetString("PasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password question  的本地化字符串。
        /// </summary>
        public static string PasswordQuestion {
            get {
                return ResourceManager.GetString("PasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length should be unbder 30  的本地化字符串。
        /// </summary>
        public static string PasswordQuestionAnswerOverMaxLength {
            get {
                return ResourceManager.GetString("PasswordQuestionAnswerOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission 的本地化字符串。
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permission Name 的本地化字符串。
        /// </summary>
        public static string PermissionName {
            get {
                return ResourceManager.GetString("PermissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone 的本地化字符串。
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registry time 的本地化字符串。
        /// </summary>
        public static string RegistryTime {
            get {
                return ResourceManager.GetString("RegistryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark 的本地化字符串。
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark&apos;s length should be less than 200 的本地化字符串。
        /// </summary>
        public static string RemarkOverMaxLength {
            get {
                return ResourceManager.GetString("RemarkOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input loginId. 的本地化字符串。
        /// </summary>
        public static string RequireLoginId {
            get {
                return ResourceManager.GetString("RequireLoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input name. 的本地化字符串。
        /// </summary>
        public static string RequireName {
            get {
                return ResourceManager.GetString("RequireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input password. 的本地化字符串。
        /// </summary>
        public static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input question&apos;s answer 的本地化字符串。
        /// </summary>
        public static string RequirePasswordAnswer {
            get {
                return ResourceManager.GetString("RequirePasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please entry question. 的本地化字符串。
        /// </summary>
        public static string RequirePasswordQuestion {
            get {
                return ResourceManager.GetString("RequirePasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please input role&apos;s name 的本地化字符串。
        /// </summary>
        public static string RequireRoleName {
            get {
                return ResourceManager.GetString("RequireRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of role&apos;s name should be less than 20 的本地化字符串。
        /// </summary>
        public static string RoleNameOverMaxLength {
            get {
                return ResourceManager.GetString("RoleNameOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of role&apos;s Remark should be less than 100 的本地化字符串。
        /// </summary>
        public static string RoleRemarkOverMaxLength {
            get {
                return ResourceManager.GetString("RoleRemarkOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time zone 的本地化字符串。
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Group 的本地化字符串。
        /// </summary>
        public static string UserGroup {
            get {
                return ResourceManager.GetString("UserGroup", resourceCulture);
            }
        }
    }
}
