//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ornament.MemberShip.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ornament.MemberShip.Languages.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Please input right format email address 的本地化字符串。
        /// </summary>
        public static string EmailNotRightFormat {
            get {
                return ResourceManager.GetString("EmailNotRightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginId should be between 6 and 20, It should be number underscrope and letter and case sense. 的本地化字符串。
        /// </summary>
        public static string LoginNotCorrectFormat {
            get {
                return ResourceManager.GetString("LoginNotCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name&apos;s length should be 1~30 的本地化字符串。
        /// </summary>
        public static string NameOverMaxLength {
            get {
                return ResourceManager.GetString("NameOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PageIndex should greater than zero or equal zero. 的本地化字符串。
        /// </summary>
        public static string PageIndex_should_greater_than_zero_ {
            get {
                return ResourceManager.GetString("PageIndex_should_greater_than_zero_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 pageSize should greater than zero. 的本地化字符串。
        /// </summary>
        public static string PageSize_should_greater_than_zero {
            get {
                return ResourceManager.GetString("PageSize_should_greater_than_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Length should be unbder 30  的本地化字符串。
        /// </summary>
        public static string PasswordQuestionAnswerOverMaxLength {
            get {
                return ResourceManager.GetString("PasswordQuestionAnswerOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remark&apos;s length should be less than 200 的本地化字符串。
        /// </summary>
        public static string RemarkOverMaxLength {
            get {
                return ResourceManager.GetString("RemarkOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input loginId. 的本地化字符串。
        /// </summary>
        public static string RequireLoginId {
            get {
                return ResourceManager.GetString("RequireLoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input name. 的本地化字符串。
        /// </summary>
        public static string RequireName {
            get {
                return ResourceManager.GetString("RequireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input password. 的本地化字符串。
        /// </summary>
        public static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input question&apos;s answer 的本地化字符串。
        /// </summary>
        public static string RequirePasswordAnswer {
            get {
                return ResourceManager.GetString("RequirePasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input question 的本地化字符串。
        /// </summary>
        public static string RequirePasswordQuestion {
            get {
                return ResourceManager.GetString("RequirePasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 please input role&apos;s name 的本地化字符串。
        /// </summary>
        public static string RequireRoleName {
            get {
                return ResourceManager.GetString("RequireRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of role&apos;s name should be less than 20 的本地化字符串。
        /// </summary>
        public static string RoleNameOverMaxLength {
            get {
                return ResourceManager.GetString("RoleNameOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The length of role&apos;s Remark should be less than 100 的本地化字符串。
        /// </summary>
        public static string RoleRemarkOverMaxLength {
            get {
                return ResourceManager.GetString("RoleRemarkOverMaxLength", resourceCulture);
            }
        }
    }
}
