//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Mvc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sitemap {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sitemap() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Mvc.sitemap", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string assign_title {
            get {
                return ResourceManager.GetString("assign.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Initialization.
        /// </summary>
        internal static string dataInit_title {
            get {
                return ResourceManager.GetString("dataInit.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Notify.
        /// </summary>
        internal static string Emails_title {
            get {
                return ResourceManager.GetString("Emails.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Log.
        /// </summary>
        internal static string eventLog_title {
            get {
                return ResourceManager.GetString("eventLog.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Roles.
        /// </summary>
        internal static string groupAssignRole_title {
            get {
                return ResourceManager.GetString("groupAssignRole.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Users.
        /// </summary>
        internal static string groupAssignUser_title {
            get {
                return ResourceManager.GetString("groupAssignUser.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Usergroup.
        /// </summary>
        internal static string groupCreate_title {
            get {
                return ResourceManager.GetString("groupCreate.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string groupEdit_title {
            get {
                return ResourceManager.GetString("groupEdit.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usergroup list.
        /// </summary>
        internal static string groupList_title {
            get {
                return ResourceManager.GetString("groupList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string home_title {
            get {
                return ResourceManager.GetString("home.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        internal static string membership_title {
            get {
                return ResourceManager.GetString("membership.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Org.
        /// </summary>
        internal static string orgCreate_title {
            get {
                return ResourceManager.GetString("orgCreate.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string orgEdit_title {
            get {
                return ResourceManager.GetString("orgEdit.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org list.
        /// </summary>
        internal static string orgList_title {
            get {
                return ResourceManager.GetString("orgList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Permission.
        /// </summary>
        internal static string permissionCreate_title {
            get {
                return ResourceManager.GetString("permissionCreate.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Permission.
        /// </summary>
        internal static string permissionEdit_title {
            get {
                return ResourceManager.GetString("permissionEdit.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission list.
        /// </summary>
        internal static string permissionList_title {
            get {
                return ResourceManager.GetString("permissionList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        internal static string personal_title {
            get {
                return ResourceManager.GetString("personal.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role.
        /// </summary>
        internal static string roleCreate_title {
            get {
                return ResourceManager.GetString("roleCreate.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string roleDelete_Title {
            get {
                return ResourceManager.GetString("roleDelete.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string roleEdit_title {
            get {
                return ResourceManager.GetString("roleEdit.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role list.
        /// </summary>
        internal static string roleList_title {
            get {
                return ResourceManager.GetString("roleList.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_title {
            get {
                return ResourceManager.GetString("settings.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string system_title {
            get {
                return ResourceManager.GetString("system.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User .
        /// </summary>
        internal static string userCreate_title {
            get {
                return ResourceManager.GetString("userCreate.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        internal static string userEdit_title {
            get {
                return ResourceManager.GetString("userEdit.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list.
        /// </summary>
        internal static string userList_title {
            get {
                return ResourceManager.GetString("userList.title", resourceCulture);
            }
        }
    }
}
