//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ornament.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ornament.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;关键信息被修改&lt;/Subject&gt;
        ///  &lt;Value&gt;
        ///    &lt;![CDATA[
        ///    &lt;p&gt;亲爱的[name]用户:
        ///
        ///    &lt;p&gt;  你已经在XXX系统修改了[content].
        ///
        ///  
        ///    &lt;p&gt;账号信息
        ///   &lt;p&gt; 登录Id:[loginId]  
        ///    
        ///
        ///   &lt;p&gt; 管理员
        /// ]]&gt;&lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string changeAccount {
            get {
                return ResourceManager.GetString("changeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;关键信息被修改&lt;/Subject&gt;
        ///    &lt;Value&gt;
        ///      &lt;![CDATA[
        ///      
        ///      
        ///&lt;![CDATA[
        ///    &lt;p&gt;亲爱的[name]用户:
        ///
        ///    &lt;p&gt;  你已经在XXX系统修改了[content].
        ///
        ///  
        ///    &lt;p&gt;账号信息
        ///   &lt;p&gt; 登录Id:[loginId]  
        ///    
        ///
        ///   &lt;p&gt; 管理员
        /// ]]&gt;
        /// &lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string changeAccount_zh {
            get {
                return ResourceManager.GetString("changeAccount_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;关键信息被修改&lt;/Subject&gt;
        ///    &lt;Value&gt; &lt;![CDATA[
        ///    &lt;p&gt;亲爱的[name]用户:
        ///
        ///    &lt;p&gt;  你已经在XXX系统修改了[content].
        ///
        ///  
        ///    &lt;p&gt;账号信息
        ///   &lt;p&gt; 登录Id:[loginId]  
        ///    
        ///
        ///   &lt;p&gt; 管理员
        /// ]]&gt;&lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string changeAccount_zh_CN {
            get {
                return ResourceManager.GetString("changeAccount_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment 的本地化字符串。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration 的本地化字符串。
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Address 的本地化字符串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish 的本地化字符串。
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;[site] Password Retrive&lt;/Subject&gt;
        ///    &lt;Value&gt; &lt;![CDATA[
        ///   &lt;p&gt; Dear [name],
        ///
        ///   &lt;p&gt; Please click following emial and reset you password again.
        ///
        ///    &lt;p&gt;[Url]
        ///
        ///
        ///    &lt;p&gt;[site] administrators group
        /// ]]&gt;&lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string forgetPassword {
            get {
                return ResourceManager.GetString("forgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;[site] 密碼重置&lt;/Subject&gt;
        ///    &lt;Value&gt; &lt;![CDATA[
        ///    &lt;p&gt;[Name]
        ///	
        ///	 &lt;p&gt;  您好，請點擊以下鏈接進行重置密碼操作
        ///    
        ///
        ///  &lt;p&gt;  [Url]
        ///
        /// &lt;p&gt;   [site]管理員團隊
        /// ]]&gt;&lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string forgetPassword_zh {
            get {
                return ResourceManager.GetString("forgetPassword_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;[site] 密码重置&lt;/Subject&gt;
        ///    &lt;Value&gt; &lt;![CDATA[
        ///  &lt;p&gt;  [name]
        ///	
        ///	 &lt;p&gt;  您好，请点击下面url进行密码重置
        ///    
        ///
        /// &lt;p&gt;   [url]
        ///
        /// &lt;p&gt;   [site]管理团队
        /// ]]&gt;&lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string forgetPassword_zh_CN {
            get {
                return ResourceManager.GetString("forgetPassword_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Friday 的本地化字符串。
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List 的本地化字符串。
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logon 的本地化字符串。
        /// </summary>
        public static string Logon {
            get {
                return ResourceManager.GetString("Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logout 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Messages 的本地化字符串。
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monday 的本地化字符串。
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone 的本地化字符串。
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous 的本地化字符串。
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Account 的本地化字符串。
        /// </summary>
        public static string Regist {
            get {
                return ResourceManager.GetString("Regist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;x-cp20936&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;��ע���û�&lt;/Subject&gt;
        ///    &lt;Value&gt;
        ///      &lt;![CDATA[�װ���[name]�û�:
        ///      
        ///  &lt;p&gt;  ���Ѿ���XXXϵͳ�ɹ�ע����һ�����˺ţ�Ϊ�����������������֤��
        ///
        ///  &lt;p&gt;  [url]
        ///
        ///
        ///    &lt;p&gt;�˺���Ϣ
        ///   &lt;p&gt; ��¼Id:[loginId]  
        ///    
        ///
        ///   &lt;p&gt; ����Ա
        /// ]]&gt;&lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string registAccount {
            get {
                return ResourceManager.GetString("registAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;新注册用户&lt;/Subject&gt;
        ///    &lt;Value&gt; &lt;![CDATA[
        ///   &lt;p&gt; 亲爱的[name]用户:
        ///
        ///   &lt;p&gt; 你已经在XXX系统成功注册了一个新账号，为了请点击下面的连接验证。
        ///
        ///  &lt;p&gt;  [url]
        ///
        ///
        ///  &lt;p&gt;  账号信息
        ///  &lt;p&gt;  登录Id:[loginId]
        ///
        ///  &lt;p&gt;  管理员
        /// ]]&gt;&lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string registAccount_zh {
            get {
                return ResourceManager.GetString("registAccount_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;新注册用户&lt;/Subject&gt;
        ///    &lt;Value&gt; &lt;![CDATA[
        ///  &lt;p&gt;  亲爱的[name]用户:
        ///
        /// &lt;p&gt;   你已经在XXX系统成功注册了一个新账号，为了请点击下面的连接验证。
        ///
        /// &lt;p&gt;   [url]
        ///
        ///
        ///   &lt;p&gt; 账号信息
        ///  &lt;p&gt;  登录Id:[loginId]   
        ///
        ///  &lt;p&gt;  管理员
        /// ]]&gt;&lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string registAccount_zh_CN {
            get {
                return ResourceManager.GetString("registAccount_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saturday 的本地化字符串。
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save successfully. 的本地化字符串。
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submitting... 的本地化字符串。
        /// </summary>
        public static string Submitting {
            get {
                return ResourceManager.GetString("Submitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sunday 的本地化字符串。
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thursday 的本地化字符串。
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tuesday 的本地化字符串。
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validate 的本地化字符串。
        /// </summary>
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;[site] notify messages&lt;/Subject&gt;
        ///  &lt;Value&gt; &lt;![CDATA[
        ///    Dear [name],
        ///
        ///	&lt;p&gt;
        ///    You eEmail has be changed, please click following Url to verify this email address.
        ///	&lt;/p&gt;
        ///
        ///    [url]
        ///
        ///	&lt;p&gt;
        ///    [site] administrator.
        ///	&lt;/p&gt;
        /// ]]&gt;&lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string verifyEmail {
            get {
                return ResourceManager.GetString("verifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;[site] 通知 &lt;/Subject&gt;
        ///    &lt;Value&gt; &lt;![CDATA[
        ///    [name]，您好
        ///
        ///	&lt;p&gt;
        ///    你的安全電子郵件已經被修改了，請點擊下面的url進行確認。
        ///	&lt;/p&gt;
        ///
        ///	&lt;p&gt;
        ///    [url]
        ///	&lt;/p&gt;
        ///
        ///	&lt;p&gt;
        ///	請不要回覆此郵件。
        ///	&lt;/P&gt;
        ///
        ///	&lt;p&gt;
        ///    [site] 管理员
        ///	&lt;/p&gt;
        /// ]]&gt;&lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string verifyEmail_zh {
            get {
                return ResourceManager.GetString("verifyEmail_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        /// &lt;Subject&gt;[site] 通知 &lt;/Subject&gt;
        ///    &lt;Value&gt; &lt;![CDATA[
        ///    [name]，您好
        ///	  &lt;p&gt;
        ///		你的安全电子邮件已经被修改。请点击下面链接进行确认
        ///		&lt;/p&gt;
        ///
        ///    &lt;p&gt;[url]&lt;/p&gt;
        ///
        ///	&lt;p&gt;请不要回复此邮件&lt;/p&gt;
        ///
        ///    &lt;p&gt;[site] 管理员&lt;/p&gt;
        /// ]]&gt;&lt;/Value&gt;  
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        public static string verifyEmail_zh_CN {
            get {
                return ResourceManager.GetString("verifyEmail_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wednesday 的本地化字符串。
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
