//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18047
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ornament.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ornament.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;新注册用户&lt;/Subject&gt;
        ///  &lt;Value&gt;
        ///    亲爱的[Name]用户:
        ///
        ///    你已经在XXX系统成功注册了一个新账号，为了请点击下面的连接验证。
        ///
        ///    [Url]
        ///
        ///
        ///    账号信息
        ///    登录Id:[LoginId]
        ///    密码:[Password]
        ///    Email:[Email]
        ///
        ///
        ///    管理员
        ///  &lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        internal static string emailChanged {
            get {
                return ResourceManager.GetString("emailChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;新注册用户&lt;/Subject&gt;
        ///  &lt;Value&gt;
        ///    亲爱的[Name]用户:
        ///
        ///    你已经在XXX系统成功注册了一个新账号，为了请点击下面的连接验证。
        ///
        ///    [Url]
        ///
        ///
        ///    账号信息
        ///    登录Id:[LoginId]
        ///    密码:[Password]
        ///    Email:[Email]
        ///
        ///
        ///    管理员
        ///  &lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        internal static string emailChanged_zh {
            get {
                return ResourceManager.GetString("emailChanged_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;新注册用户&lt;/Subject&gt;
        ///  &lt;Value&gt;
        ///    亲爱的[Name]用户:
        ///
        ///    你已经在XXX系统成功注册了一个新账号，为了请点击下面的连接验证。
        ///
        ///    [Url]
        ///
        ///
        ///    账号信息
        ///    登录Id:[LoginId]
        ///    密码:[Password]
        ///    Email:[Email]
        ///
        ///
        ///    管理员
        ///  &lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        internal static string emailChanged_zh_CN {
            get {
                return ResourceManager.GetString("emailChanged_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;新注册用户&lt;/Subject&gt;
        ///  &lt;Value&gt;
        ///    亲爱的[Name]用户:
        ///
        ///    你已经在XXX系统成功注册了一个新账号，为了请点击下面的连接验证。
        ///
        ///    [Url]
        ///
        ///
        ///    账号信息
        ///    登录Id:[LoginId]
        ///    密码:[Password]
        ///    Email:[Email]
        ///
        ///
        ///    管理员
        ///  &lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        internal static string forgetPassword {
            get {
                return ResourceManager.GetString("forgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;新注册用户&lt;/Subject&gt;
        ///  &lt;Value&gt;
        ///    亲爱的[Name]用户:
        ///
        ///    你已经在XXX系统成功注册了一个新账号，为了请点击下面的连接验证。
        ///
        ///    [Url]
        ///
        ///
        ///    账号信息
        ///    登录Id:[LoginId]
        ///    密码:[Password]
        ///    Email:[Email]
        ///
        ///
        ///    管理员
        ///  &lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        internal static string forgetPassword_zh {
            get {
                return ResourceManager.GetString("forgetPassword_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;新注册用户&lt;/Subject&gt;
        ///  &lt;Value&gt;
        ///    亲爱的[Name]用户:
        ///
        ///    你已经在XXX系统成功注册了一个新账号，为了请点击下面的连接验证。
        ///
        ///    [Url]
        ///
        ///
        ///    账号信息
        ///    登录Id:[LoginId]
        ///    密码:[Password]
        ///    Email:[Email]
        ///
        ///
        ///    管理员
        ///  &lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        internal static string forgetPassword_zh_CN {
            get {
                return ResourceManager.GetString("forgetPassword_zh_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;新注册用户&lt;/Subject&gt;
        ///  &lt;Value&gt;
        ///    亲爱的[Name]用户:
        ///
        ///    你已经在XXX系统成功注册了一个新账号，为了请点击下面的连接验证。
        ///
        ///    [Url]
        ///
        ///
        ///    账号信息
        ///    登录Id:[LoginId]
        ///    密码:[Password]
        ///    Email:[Email]
        ///
        ///
        ///    管理员
        ///  &lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        internal static string registAccount {
            get {
                return ResourceManager.GetString("registAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;新注册用户&lt;/Subject&gt;
        ///  &lt;Value&gt;
        ///    亲爱的[Name]用户:
        ///
        ///    你已经在XXX系统成功注册了一个新账号，为了请点击下面的连接验证。
        ///
        ///    [Url]
        ///
        ///
        ///    账号信息
        ///    登录Id:[LoginId]
        ///    密码:[Password]
        ///    Email:[Email]
        ///
        ///
        ///    管理员
        ///  &lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        internal static string registAccount_zh {
            get {
                return ResourceManager.GetString("registAccount_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Content xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Subject&gt;新注册用户&lt;/Subject&gt;
        ///  &lt;Value&gt;
        ///    亲爱的[Name]用户:
        ///
        ///    你已经在XXX系统成功注册了一个新账号，为了请点击下面的连接验证。
        ///
        ///    [Url]
        ///
        ///
        ///    账号信息
        ///    登录Id:[LoginId]
        ///    密码:[Password]
        ///    Email:[Email]
        ///
        ///
        ///    管理员
        ///  &lt;/Value&gt;
        ///&lt;/Content&gt; 的本地化字符串。
        /// </summary>
        internal static string registAccount_zh_CN {
            get {
                return ResourceManager.GetString("registAccount_zh_CN", resourceCulture);
            }
        }
    }
}
