//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ornament.MemberShip.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ornament.MemberShip.Languages.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input right format email address.
        /// </summary>
        public static string EmailNotRightFormat {
            get {
                return ResourceManager.GetString("EmailNotRightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoginId should be between 6 and 20, It should be number underscrope and letter and case sense..
        /// </summary>
        public static string LoginNotCorrectFormat {
            get {
                return ResourceManager.GetString("LoginNotCorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name&apos;s length should be 1~30.
        /// </summary>
        public static string NameOverMaxLength {
            get {
                return ResourceManager.GetString("NameOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length should be unbder 30 .
        /// </summary>
        public static string PasswordQuestionAnswerOverMaxLength {
            get {
                return ResourceManager.GetString("PasswordQuestionAnswerOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark&apos;s length should be less than 200.
        /// </summary>
        public static string RemarkOverMaxLength {
            get {
                return ResourceManager.GetString("RemarkOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input loginId..
        /// </summary>
        public static string RequireLoginId {
            get {
                return ResourceManager.GetString("RequireLoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input name..
        /// </summary>
        public static string RequireName {
            get {
                return ResourceManager.GetString("RequireName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input password..
        /// </summary>
        public static string RequirePassword {
            get {
                return ResourceManager.GetString("RequirePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input question&apos;s answer.
        /// </summary>
        public static string RequirePasswordAnswer {
            get {
                return ResourceManager.GetString("RequirePasswordAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input question.
        /// </summary>
        public static string RequirePasswordQuestion {
            get {
                return ResourceManager.GetString("RequirePasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please input role&apos;s name.
        /// </summary>
        public static string RequireRoleName {
            get {
                return ResourceManager.GetString("RequireRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of role&apos;s name should be less than 20.
        /// </summary>
        public static string RoleNameOverMaxLength {
            get {
                return ResourceManager.GetString("RoleNameOverMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of role&apos;s Remark should be less than 100.
        /// </summary>
        public static string RoleRemarkOverMaxLength {
            get {
                return ResourceManager.GetString("RoleRemarkOverMaxLength", resourceCulture);
            }
        }
    }
}
