//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ornament.MemberShip.Plugin.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ornament.MemberShip.Plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Setting 的本地化字符串。
        /// </summary>
        public static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input confirm password. 的本地化字符串。
        /// </summary>
        public static string alert_Require_ConfirmPassword {
            get {
                return ResourceManager.GetString("alert_Require_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password doesn&apos;t match the confirmation. 的本地化字符串。
        /// </summary>
        public static string alertMsg_Confirm_Password_Not_Equal_New_password {
            get {
                return ResourceManager.GetString("alertMsg_Confirm_Password_Not_Equal_New_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This email has been used by another user. 的本地化字符串。
        /// </summary>
        public static string alertMsg_duplicate_Email {
            get {
                return ResourceManager.GetString("alertMsg_duplicate_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logind is exist, please choice another one. 的本地化字符串。
        /// </summary>
        public static string alertMsg_duplicate_loginId {
            get {
                return ResourceManager.GetString("alertMsg_duplicate_loginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role name is exist, please input another one. 的本地化字符串。
        /// </summary>
        public static string alertMsg_duplicate_roleName {
            get {
                return ResourceManager.GetString("alertMsg_duplicate_roleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Password isn&apos;t right. 的本地化字符串。
        /// </summary>
        public static string alertMsg_OldPasswordNotRight {
            get {
                return ResourceManager.GetString("alertMsg_OldPasswordNotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password is too short (minimum is {0} characters). 的本地化字符串。
        /// </summary>
        public static string alertMsg_Password_length_not_right {
            get {
                return ResourceManager.GetString("alertMsg_Password_length_not_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 permission denied can not access users 的本地化字符串。
        /// </summary>
        public static string alertMsg_PermissionNotPermintAccessUsers {
            get {
                return ResourceManager.GetString("alertMsg_PermissionNotPermintAccessUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password can&apos;t be blank. 的本地化字符串。
        /// </summary>
        public static string alertMsg_Require_NewPassword {
            get {
                return ResourceManager.GetString("alertMsg_Require_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Password can&apos;t be blank. 的本地化字符串。
        /// </summary>
        public static string alertMsg_Require_OldPassword {
            get {
                return ResourceManager.GetString("alertMsg_Require_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input login ID or email address. 的本地化字符串。
        /// </summary>
        public static string alertMsg_RequireAccountOrEmail {
            get {
                return ResourceManager.GetString("alertMsg_RequireAccountOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input verify code. 的本地化字符串。
        /// </summary>
        public static string alertMsg_requireVerifyCode {
            get {
                return ResourceManager.GetString("alertMsg_requireVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input correct email address. 的本地化字符串。
        /// </summary>
        public static string altMessage_EmailFormatNotCorrect {
            get {
                return ResourceManager.GetString("altMessage_EmailFormatNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assign Users 的本地化字符串。
        /// </summary>
        public static string AssignUserGroup {
            get {
                return ResourceManager.GetString("AssignUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Password 的本地化字符串。
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Re-enter Password 的本地化字符串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create time 的本地化字符串。
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Password 的本地化字符串。
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify code is expire. 的本地化字符串。
        /// </summary>
        public static string error_expireVerifyCode {
            get {
                return ResourceManager.GetString("error_expireVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input email. 的本地化字符串。
        /// </summary>
        public static string error_missingEmailAddress {
            get {
                return ResourceManager.GetString("error_missingEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input login id. 的本地化字符串。
        /// </summary>
        public static string error_MissLoginId {
            get {
                return ResourceManager.GetString("error_MissLoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input password. 的本地化字符串。
        /// </summary>
        public static string error_MissPassword {
            get {
                return ResourceManager.GetString("error_MissPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Code not match. 的本地化字符串。
        /// </summary>
        public static string error_notMatchVerifyCode {
            get {
                return ResourceManager.GetString("error_notMatchVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User is not approved. 的本地化字符串。
        /// </summary>
        public static string error_UserIsNotApproved {
            get {
                return ResourceManager.GetString("error_UserIsNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm can&apos;t be blank. 的本地化字符串。
        /// </summary>
        public static string input_password_again {
            get {
                return ResourceManager.GetString("input_password_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Or Email 的本地化字符串。
        /// </summary>
        public static string label_AccountOrEmail {
            get {
                return ResourceManager.GetString("label_AccountOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Child Org&apos;s Count 的本地化字符串。
        /// </summary>
        public static string Org_OrgCount_Child_Org_s_Count {
            get {
                return ResourceManager.GetString("Org_OrgCount_Child_Org_s_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registry time 的本地化字符串。
        /// </summary>
        public static string RegistryTime {
            get {
                return ResourceManager.GetString("RegistryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember me 的本地化字符串。
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Code 的本地化字符串。
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verify Email if changed 的本地化字符串。
        /// </summary>
        public static string VerifyEmail {
            get {
                return ResourceManager.GetString("VerifyEmail", resourceCulture);
            }
        }
    }
}
