//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ornament.MemberShip.Plugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ornament.MemberShip.Plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input confirm password..
        /// </summary>
        public static string alert_Require_ConfirmPassword {
            get {
                return ResourceManager.GetString("alert_Require_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password doesn&apos;t match the confirmation..
        /// </summary>
        public static string alertMsg_Confirm_Password_Not_Equal_New_password {
            get {
                return ResourceManager.GetString("alertMsg_Confirm_Password_Not_Equal_New_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email has been used by another user..
        /// </summary>
        public static string alertMsg_duplicate_Email {
            get {
                return ResourceManager.GetString("alertMsg_duplicate_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logind is exist, please choice another one..
        /// </summary>
        public static string alertMsg_duplicate_loginId {
            get {
                return ResourceManager.GetString("alertMsg_duplicate_loginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name is exist, please input another one..
        /// </summary>
        public static string alertMsg_duplicate_roleName {
            get {
                return ResourceManager.GetString("alertMsg_duplicate_roleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password isn&apos;t right..
        /// </summary>
        public static string alertMsg_OldPasswordNotRight {
            get {
                return ResourceManager.GetString("alertMsg_OldPasswordNotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too short (minimum is {0} characters)..
        /// </summary>
        public static string alertMsg_Password_length_not_right {
            get {
                return ResourceManager.GetString("alertMsg_Password_length_not_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permission denied can not access users.
        /// </summary>
        public static string alertMsg_PermissionNotPermintAccessUsers {
            get {
                return ResourceManager.GetString("alertMsg_PermissionNotPermintAccessUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password can&apos;t be blank..
        /// </summary>
        public static string alertMsg_Require_NewPassword {
            get {
                return ResourceManager.GetString("alertMsg_Require_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password can&apos;t be blank..
        /// </summary>
        public static string alertMsg_Require_OldPassword {
            get {
                return ResourceManager.GetString("alertMsg_Require_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input login ID or email address..
        /// </summary>
        public static string alertMsg_RequireAccountOrEmail {
            get {
                return ResourceManager.GetString("alertMsg_RequireAccountOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input verify code..
        /// </summary>
        public static string alertMsg_requireVerifyCode {
            get {
                return ResourceManager.GetString("alertMsg_requireVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input correct email address..
        /// </summary>
        public static string altMessage_EmailFormatNotCorrect {
            get {
                return ResourceManager.GetString("altMessage_EmailFormatNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Users.
        /// </summary>
        public static string AssignUserGroup {
            get {
                return ResourceManager.GetString("AssignUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password agan.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create time.
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login id or Password is not match..
        /// </summary>
        public static string error_LoginError {
            get {
                return ResourceManager.GetString("error_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input email..
        /// </summary>
        public static string error_missingEmailAddress {
            get {
                return ResourceManager.GetString("error_missingEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input login id..
        /// </summary>
        public static string error_MissLoginId {
            get {
                return ResourceManager.GetString("error_MissLoginId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input password..
        /// </summary>
        public static string error_MissPassword {
            get {
                return ResourceManager.GetString("error_MissPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Code not match..
        /// </summary>
        public static string error_notMatchVerifyCode {
            get {
                return ResourceManager.GetString("error_notMatchVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is lockout..
        /// </summary>
        public static string error_UserIsLockout {
            get {
                return ResourceManager.GetString("error_UserIsLockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not approved..
        /// </summary>
        public static string error_UserIsNotApproved {
            get {
                return ResourceManager.GetString("error_UserIsNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm can&apos;t be blank..
        /// </summary>
        public static string input_password_again {
            get {
                return ResourceManager.GetString("input_password_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Or Email.
        /// </summary>
        public static string label_AccountOrEmail {
            get {
                return ResourceManager.GetString("label_AccountOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Org&apos;s Count.
        /// </summary>
        public static string Org_OrgCount_Child_Org_s_Count {
            get {
                return ResourceManager.GetString("Org_OrgCount_Child_Org_s_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry time.
        /// </summary>
        public static string RegistryTime {
            get {
                return ResourceManager.GetString("RegistryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Code.
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Email if changed.
        /// </summary>
        public static string VerifyEmail {
            get {
                return ResourceManager.GetString("VerifyEmail", resourceCulture);
            }
        }
    }
}
